$(document).ready(function(){
	$("#footer1").html("<footer class='navbar-default navbar-fixed-bottom' style='background-color: rgba(0, 0, 0, 0.02);'><h1 class='h1p'><span style='color: #A6A6A6; font-size: 25px;'>S Plus </span><span style='color: #606060; font-size: 25px;'>Group Limited </span><a href='https://goo.gl/maps/GL8nn3N3uX52' target='_blank'><b><h4 class='h4p'><span style='color: #A6A6A6'>Room 2201 </span><span style='color: #F79646'>| </span><span style='color: #A6A6A6'>Tower Two </span><span style='color: #F79646'>| </span><span style='color: #A6A6A6'>Times Square </span><span style='color: #F79646'>| </span><span style='color: #A6A6A6'>1 Matheson Street </span><span style='color: #F79646'>| </span><span style='color: #A6A6A6'>Causeway Bay </span><span style='color: #F79646'>| </span><span style='color: #A6A6A6'>Hong Kong</span></h4></b></a></h1><span style='color:#A6A6A6; font-size: 15px'>Copyright 2017.  All rights reserved <span style='color:#F79646'>|</span> <a href='#' id='terms'><script></script>Terms and Conditions</a> <br /><br />   </span></footer>");
	$("#terms").click(function(){
		confirm("Operation\nThis website is operated by S Plus Group Limited. All inquiries may be directed to:\nS Plus Group Limited\nSuite 2201, Tower 2, Times Square\n1 Matheson Street, Causeway Bay\nHong Kong, S.A.R., China\nor \ninfo@splusgroup.net\n\nUsage\nYour use of this website is governed by these terms and conditions.  Please take the time to review them. Terms and Conditions may change from time to time.  Users should routinely check for changes to the Terms and Conditions.\n\nYour use of www.splusgroup.net constitutes your agreement to follow these rules and to be bound by them. They apply to the entirety of the website and its contents.  If you do not agree with any of these terms and conditions, do not use the www.splusgroup.net website.\n\n\n");
		confirm("General \nThis website and its contents on this website are intended to provide general information only.  Therein the information, product and activity mentioned is related to Hong Kong and to S Plus Group Limited colleagues, clients and potential customers.  Such information may be neither relevant nor appropriate for people located in locations outside of Hong Kong.  S Plus Group Limited have made every effort to be as accurate as possible, however, S Plus Group Limited makes no warranties, either express or implied, as to the accuracy of the information contained in any of the materials on this website.\n\n\n"); 
		confirm("Ownership of rights\n\nAll rights, including copyright, in this website are owned by or licensed to S Plus Group Limited.  The materials found on www.splusgroup.net including but not limited to all text, graphics, drawings, photographs and data in whatever form are owned by S Plus Group Limited or related companies or licensors who have reserved their intellectual property rights.\n\nAny use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of S Plus Group Limited. You may not modify, reproduce, distribute, re-post or make available to the public anything on this website for any purpose.\n\n\nVirus to your Computer\nS Plus Group Limited makes every effort to ensure that this website is free from bugs or viruses. We do not guarantee that your use of this website won’t cause damage to your computer and shall not be liable for loss or damage of either equipment or data which may arise because of using this website.\n\n\n");
		confirm("Links to other websites\nwww.splusgroup.net  may from time to time contain links to other websites of interest.  S Plus Group Limited cannot vet or have any control over their contents, therefore, S Plus Group Limited shall not accept any liability in respect of the use of these websites.\n\n\n\nLast updated on 25 April 2017");
		

		
	})
});

